// Code generated by ent, DO NOT EDIT.

package payment

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the payment type in the database.
	Label = "payment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldWalletAddress holds the string denoting the wallet_address field in the database.
	FieldWalletAddress = "wallet_address"
	// FieldSolReference holds the string denoting the sol_reference field in the database.
	FieldSolReference = "sol_reference"
	// FieldAddressIndex holds the string denoting the address_index field in the database.
	FieldAddressIndex = "address_index"
	// FieldAmountCrypto holds the string denoting the amount_crypto field in the database.
	FieldAmountCrypto = "amount_crypto"
	// FieldCurrencyCrypto holds the string denoting the currency_crypto field in the database.
	FieldCurrencyCrypto = "currency_crypto"
	// FieldAmountFiat holds the string denoting the amount_fiat field in the database.
	FieldAmountFiat = "amount_fiat"
	// FieldCurrencyFiat holds the string denoting the currency_fiat field in the database.
	FieldCurrencyFiat = "currency_fiat"
	// FieldReceivedAmount holds the string denoting the received_amount field in the database.
	FieldReceivedAmount = "received_amount"
	// FieldTransactionHash holds the string denoting the transaction_hash field in the database.
	FieldTransactionHash = "transaction_hash"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the payment in the database.
	Table = "payments"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "payments"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for payment fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldUserID,
	FieldWalletAddress,
	FieldSolReference,
	FieldAddressIndex,
	FieldAmountCrypto,
	FieldCurrencyCrypto,
	FieldAmountFiat,
	FieldCurrencyFiat,
	FieldReceivedAmount,
	FieldTransactionHash,
	FieldStatus,
	FieldExpiresAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// DefaultAddressIndex holds the default value on creation for the "address_index" field.
	DefaultAddressIndex int
	// DefaultExpiresAt holds the default value on creation for the "expires_at" field.
	DefaultExpiresAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Status defines the type for the "status" enum field.
type Status string

// StatusPENDING is the default value of the Status enum.
const DefaultStatus = StatusPENDING

// Status values.
const (
	StatusPENDING    Status = "PENDING"
	StatusCONFIRMING Status = "CONFIRMING"
	StatusPAID       Status = "PAID"
	StatusEXPIRED    Status = "EXPIRED"
	StatusREFUNDED   Status = "REFUNDED"
	StatusCASHED_OUT Status = "CASHED_OUT"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPENDING, StatusCONFIRMING, StatusPAID, StatusEXPIRED, StatusREFUNDED, StatusCASHED_OUT:
		return nil
	default:
		return fmt.Errorf("payment: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Payment queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByWalletAddress orders the results by the wallet_address field.
func ByWalletAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWalletAddress, opts...).ToFunc()
}

// BySolReference orders the results by the sol_reference field.
func BySolReference(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSolReference, opts...).ToFunc()
}

// ByAddressIndex orders the results by the address_index field.
func ByAddressIndex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAddressIndex, opts...).ToFunc()
}

// ByAmountCrypto orders the results by the amount_crypto field.
func ByAmountCrypto(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmountCrypto, opts...).ToFunc()
}

// ByCurrencyCrypto orders the results by the currency_crypto field.
func ByCurrencyCrypto(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrencyCrypto, opts...).ToFunc()
}

// ByAmountFiat orders the results by the amount_fiat field.
func ByAmountFiat(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmountFiat, opts...).ToFunc()
}

// ByCurrencyFiat orders the results by the currency_fiat field.
func ByCurrencyFiat(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrencyFiat, opts...).ToFunc()
}

// ByReceivedAmount orders the results by the received_amount field.
func ByReceivedAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReceivedAmount, opts...).ToFunc()
}

// ByTransactionHash orders the results by the transaction_hash field.
func ByTransactionHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTransactionHash, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
