// Code generated by ent, DO NOT EDIT.

package payment

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/szerookii/litepay/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Payment {
	return predicate.Payment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Payment {
	return predicate.Payment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Payment {
	return predicate.Payment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Payment {
	return predicate.Payment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Payment {
	return predicate.Payment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Payment {
	return predicate.Payment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Payment {
	return predicate.Payment(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldUpdateTime, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldUserID, v))
}

// WalletAddress applies equality check predicate on the "wallet_address" field. It's identical to WalletAddressEQ.
func WalletAddress(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldWalletAddress, v))
}

// SolReference applies equality check predicate on the "sol_reference" field. It's identical to SolReferenceEQ.
func SolReference(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldSolReference, v))
}

// AddressIndex applies equality check predicate on the "address_index" field. It's identical to AddressIndexEQ.
func AddressIndex(v int) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldAddressIndex, v))
}

// AmountCrypto applies equality check predicate on the "amount_crypto" field. It's identical to AmountCryptoEQ.
func AmountCrypto(v float64) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldAmountCrypto, v))
}

// CurrencyCrypto applies equality check predicate on the "currency_crypto" field. It's identical to CurrencyCryptoEQ.
func CurrencyCrypto(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldCurrencyCrypto, v))
}

// AmountFiat applies equality check predicate on the "amount_fiat" field. It's identical to AmountFiatEQ.
func AmountFiat(v float64) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldAmountFiat, v))
}

// CurrencyFiat applies equality check predicate on the "currency_fiat" field. It's identical to CurrencyFiatEQ.
func CurrencyFiat(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldCurrencyFiat, v))
}

// ReceivedAmount applies equality check predicate on the "received_amount" field. It's identical to ReceivedAmountEQ.
func ReceivedAmount(v float64) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldReceivedAmount, v))
}

// TransactionHash applies equality check predicate on the "transaction_hash" field. It's identical to TransactionHashEQ.
func TransactionHash(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldTransactionHash, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldExpiresAt, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldLTE(FieldUpdateTime, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.Payment {
	return predicate.Payment(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.Payment {
	return predicate.Payment(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.Payment {
	return predicate.Payment(sql.FieldNotIn(FieldUserID, vs...))
}

// WalletAddressEQ applies the EQ predicate on the "wallet_address" field.
func WalletAddressEQ(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldWalletAddress, v))
}

// WalletAddressNEQ applies the NEQ predicate on the "wallet_address" field.
func WalletAddressNEQ(v string) predicate.Payment {
	return predicate.Payment(sql.FieldNEQ(FieldWalletAddress, v))
}

// WalletAddressIn applies the In predicate on the "wallet_address" field.
func WalletAddressIn(vs ...string) predicate.Payment {
	return predicate.Payment(sql.FieldIn(FieldWalletAddress, vs...))
}

// WalletAddressNotIn applies the NotIn predicate on the "wallet_address" field.
func WalletAddressNotIn(vs ...string) predicate.Payment {
	return predicate.Payment(sql.FieldNotIn(FieldWalletAddress, vs...))
}

// WalletAddressGT applies the GT predicate on the "wallet_address" field.
func WalletAddressGT(v string) predicate.Payment {
	return predicate.Payment(sql.FieldGT(FieldWalletAddress, v))
}

// WalletAddressGTE applies the GTE predicate on the "wallet_address" field.
func WalletAddressGTE(v string) predicate.Payment {
	return predicate.Payment(sql.FieldGTE(FieldWalletAddress, v))
}

// WalletAddressLT applies the LT predicate on the "wallet_address" field.
func WalletAddressLT(v string) predicate.Payment {
	return predicate.Payment(sql.FieldLT(FieldWalletAddress, v))
}

// WalletAddressLTE applies the LTE predicate on the "wallet_address" field.
func WalletAddressLTE(v string) predicate.Payment {
	return predicate.Payment(sql.FieldLTE(FieldWalletAddress, v))
}

// WalletAddressContains applies the Contains predicate on the "wallet_address" field.
func WalletAddressContains(v string) predicate.Payment {
	return predicate.Payment(sql.FieldContains(FieldWalletAddress, v))
}

// WalletAddressHasPrefix applies the HasPrefix predicate on the "wallet_address" field.
func WalletAddressHasPrefix(v string) predicate.Payment {
	return predicate.Payment(sql.FieldHasPrefix(FieldWalletAddress, v))
}

// WalletAddressHasSuffix applies the HasSuffix predicate on the "wallet_address" field.
func WalletAddressHasSuffix(v string) predicate.Payment {
	return predicate.Payment(sql.FieldHasSuffix(FieldWalletAddress, v))
}

// WalletAddressEqualFold applies the EqualFold predicate on the "wallet_address" field.
func WalletAddressEqualFold(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEqualFold(FieldWalletAddress, v))
}

// WalletAddressContainsFold applies the ContainsFold predicate on the "wallet_address" field.
func WalletAddressContainsFold(v string) predicate.Payment {
	return predicate.Payment(sql.FieldContainsFold(FieldWalletAddress, v))
}

// SolReferenceEQ applies the EQ predicate on the "sol_reference" field.
func SolReferenceEQ(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldSolReference, v))
}

// SolReferenceNEQ applies the NEQ predicate on the "sol_reference" field.
func SolReferenceNEQ(v string) predicate.Payment {
	return predicate.Payment(sql.FieldNEQ(FieldSolReference, v))
}

// SolReferenceIn applies the In predicate on the "sol_reference" field.
func SolReferenceIn(vs ...string) predicate.Payment {
	return predicate.Payment(sql.FieldIn(FieldSolReference, vs...))
}

// SolReferenceNotIn applies the NotIn predicate on the "sol_reference" field.
func SolReferenceNotIn(vs ...string) predicate.Payment {
	return predicate.Payment(sql.FieldNotIn(FieldSolReference, vs...))
}

// SolReferenceGT applies the GT predicate on the "sol_reference" field.
func SolReferenceGT(v string) predicate.Payment {
	return predicate.Payment(sql.FieldGT(FieldSolReference, v))
}

// SolReferenceGTE applies the GTE predicate on the "sol_reference" field.
func SolReferenceGTE(v string) predicate.Payment {
	return predicate.Payment(sql.FieldGTE(FieldSolReference, v))
}

// SolReferenceLT applies the LT predicate on the "sol_reference" field.
func SolReferenceLT(v string) predicate.Payment {
	return predicate.Payment(sql.FieldLT(FieldSolReference, v))
}

// SolReferenceLTE applies the LTE predicate on the "sol_reference" field.
func SolReferenceLTE(v string) predicate.Payment {
	return predicate.Payment(sql.FieldLTE(FieldSolReference, v))
}

// SolReferenceContains applies the Contains predicate on the "sol_reference" field.
func SolReferenceContains(v string) predicate.Payment {
	return predicate.Payment(sql.FieldContains(FieldSolReference, v))
}

// SolReferenceHasPrefix applies the HasPrefix predicate on the "sol_reference" field.
func SolReferenceHasPrefix(v string) predicate.Payment {
	return predicate.Payment(sql.FieldHasPrefix(FieldSolReference, v))
}

// SolReferenceHasSuffix applies the HasSuffix predicate on the "sol_reference" field.
func SolReferenceHasSuffix(v string) predicate.Payment {
	return predicate.Payment(sql.FieldHasSuffix(FieldSolReference, v))
}

// SolReferenceIsNil applies the IsNil predicate on the "sol_reference" field.
func SolReferenceIsNil() predicate.Payment {
	return predicate.Payment(sql.FieldIsNull(FieldSolReference))
}

// SolReferenceNotNil applies the NotNil predicate on the "sol_reference" field.
func SolReferenceNotNil() predicate.Payment {
	return predicate.Payment(sql.FieldNotNull(FieldSolReference))
}

// SolReferenceEqualFold applies the EqualFold predicate on the "sol_reference" field.
func SolReferenceEqualFold(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEqualFold(FieldSolReference, v))
}

// SolReferenceContainsFold applies the ContainsFold predicate on the "sol_reference" field.
func SolReferenceContainsFold(v string) predicate.Payment {
	return predicate.Payment(sql.FieldContainsFold(FieldSolReference, v))
}

// AddressIndexEQ applies the EQ predicate on the "address_index" field.
func AddressIndexEQ(v int) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldAddressIndex, v))
}

// AddressIndexNEQ applies the NEQ predicate on the "address_index" field.
func AddressIndexNEQ(v int) predicate.Payment {
	return predicate.Payment(sql.FieldNEQ(FieldAddressIndex, v))
}

// AddressIndexIn applies the In predicate on the "address_index" field.
func AddressIndexIn(vs ...int) predicate.Payment {
	return predicate.Payment(sql.FieldIn(FieldAddressIndex, vs...))
}

// AddressIndexNotIn applies the NotIn predicate on the "address_index" field.
func AddressIndexNotIn(vs ...int) predicate.Payment {
	return predicate.Payment(sql.FieldNotIn(FieldAddressIndex, vs...))
}

// AddressIndexGT applies the GT predicate on the "address_index" field.
func AddressIndexGT(v int) predicate.Payment {
	return predicate.Payment(sql.FieldGT(FieldAddressIndex, v))
}

// AddressIndexGTE applies the GTE predicate on the "address_index" field.
func AddressIndexGTE(v int) predicate.Payment {
	return predicate.Payment(sql.FieldGTE(FieldAddressIndex, v))
}

// AddressIndexLT applies the LT predicate on the "address_index" field.
func AddressIndexLT(v int) predicate.Payment {
	return predicate.Payment(sql.FieldLT(FieldAddressIndex, v))
}

// AddressIndexLTE applies the LTE predicate on the "address_index" field.
func AddressIndexLTE(v int) predicate.Payment {
	return predicate.Payment(sql.FieldLTE(FieldAddressIndex, v))
}

// AmountCryptoEQ applies the EQ predicate on the "amount_crypto" field.
func AmountCryptoEQ(v float64) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldAmountCrypto, v))
}

// AmountCryptoNEQ applies the NEQ predicate on the "amount_crypto" field.
func AmountCryptoNEQ(v float64) predicate.Payment {
	return predicate.Payment(sql.FieldNEQ(FieldAmountCrypto, v))
}

// AmountCryptoIn applies the In predicate on the "amount_crypto" field.
func AmountCryptoIn(vs ...float64) predicate.Payment {
	return predicate.Payment(sql.FieldIn(FieldAmountCrypto, vs...))
}

// AmountCryptoNotIn applies the NotIn predicate on the "amount_crypto" field.
func AmountCryptoNotIn(vs ...float64) predicate.Payment {
	return predicate.Payment(sql.FieldNotIn(FieldAmountCrypto, vs...))
}

// AmountCryptoGT applies the GT predicate on the "amount_crypto" field.
func AmountCryptoGT(v float64) predicate.Payment {
	return predicate.Payment(sql.FieldGT(FieldAmountCrypto, v))
}

// AmountCryptoGTE applies the GTE predicate on the "amount_crypto" field.
func AmountCryptoGTE(v float64) predicate.Payment {
	return predicate.Payment(sql.FieldGTE(FieldAmountCrypto, v))
}

// AmountCryptoLT applies the LT predicate on the "amount_crypto" field.
func AmountCryptoLT(v float64) predicate.Payment {
	return predicate.Payment(sql.FieldLT(FieldAmountCrypto, v))
}

// AmountCryptoLTE applies the LTE predicate on the "amount_crypto" field.
func AmountCryptoLTE(v float64) predicate.Payment {
	return predicate.Payment(sql.FieldLTE(FieldAmountCrypto, v))
}

// CurrencyCryptoEQ applies the EQ predicate on the "currency_crypto" field.
func CurrencyCryptoEQ(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldCurrencyCrypto, v))
}

// CurrencyCryptoNEQ applies the NEQ predicate on the "currency_crypto" field.
func CurrencyCryptoNEQ(v string) predicate.Payment {
	return predicate.Payment(sql.FieldNEQ(FieldCurrencyCrypto, v))
}

// CurrencyCryptoIn applies the In predicate on the "currency_crypto" field.
func CurrencyCryptoIn(vs ...string) predicate.Payment {
	return predicate.Payment(sql.FieldIn(FieldCurrencyCrypto, vs...))
}

// CurrencyCryptoNotIn applies the NotIn predicate on the "currency_crypto" field.
func CurrencyCryptoNotIn(vs ...string) predicate.Payment {
	return predicate.Payment(sql.FieldNotIn(FieldCurrencyCrypto, vs...))
}

// CurrencyCryptoGT applies the GT predicate on the "currency_crypto" field.
func CurrencyCryptoGT(v string) predicate.Payment {
	return predicate.Payment(sql.FieldGT(FieldCurrencyCrypto, v))
}

// CurrencyCryptoGTE applies the GTE predicate on the "currency_crypto" field.
func CurrencyCryptoGTE(v string) predicate.Payment {
	return predicate.Payment(sql.FieldGTE(FieldCurrencyCrypto, v))
}

// CurrencyCryptoLT applies the LT predicate on the "currency_crypto" field.
func CurrencyCryptoLT(v string) predicate.Payment {
	return predicate.Payment(sql.FieldLT(FieldCurrencyCrypto, v))
}

// CurrencyCryptoLTE applies the LTE predicate on the "currency_crypto" field.
func CurrencyCryptoLTE(v string) predicate.Payment {
	return predicate.Payment(sql.FieldLTE(FieldCurrencyCrypto, v))
}

// CurrencyCryptoContains applies the Contains predicate on the "currency_crypto" field.
func CurrencyCryptoContains(v string) predicate.Payment {
	return predicate.Payment(sql.FieldContains(FieldCurrencyCrypto, v))
}

// CurrencyCryptoHasPrefix applies the HasPrefix predicate on the "currency_crypto" field.
func CurrencyCryptoHasPrefix(v string) predicate.Payment {
	return predicate.Payment(sql.FieldHasPrefix(FieldCurrencyCrypto, v))
}

// CurrencyCryptoHasSuffix applies the HasSuffix predicate on the "currency_crypto" field.
func CurrencyCryptoHasSuffix(v string) predicate.Payment {
	return predicate.Payment(sql.FieldHasSuffix(FieldCurrencyCrypto, v))
}

// CurrencyCryptoEqualFold applies the EqualFold predicate on the "currency_crypto" field.
func CurrencyCryptoEqualFold(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEqualFold(FieldCurrencyCrypto, v))
}

// CurrencyCryptoContainsFold applies the ContainsFold predicate on the "currency_crypto" field.
func CurrencyCryptoContainsFold(v string) predicate.Payment {
	return predicate.Payment(sql.FieldContainsFold(FieldCurrencyCrypto, v))
}

// AmountFiatEQ applies the EQ predicate on the "amount_fiat" field.
func AmountFiatEQ(v float64) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldAmountFiat, v))
}

// AmountFiatNEQ applies the NEQ predicate on the "amount_fiat" field.
func AmountFiatNEQ(v float64) predicate.Payment {
	return predicate.Payment(sql.FieldNEQ(FieldAmountFiat, v))
}

// AmountFiatIn applies the In predicate on the "amount_fiat" field.
func AmountFiatIn(vs ...float64) predicate.Payment {
	return predicate.Payment(sql.FieldIn(FieldAmountFiat, vs...))
}

// AmountFiatNotIn applies the NotIn predicate on the "amount_fiat" field.
func AmountFiatNotIn(vs ...float64) predicate.Payment {
	return predicate.Payment(sql.FieldNotIn(FieldAmountFiat, vs...))
}

// AmountFiatGT applies the GT predicate on the "amount_fiat" field.
func AmountFiatGT(v float64) predicate.Payment {
	return predicate.Payment(sql.FieldGT(FieldAmountFiat, v))
}

// AmountFiatGTE applies the GTE predicate on the "amount_fiat" field.
func AmountFiatGTE(v float64) predicate.Payment {
	return predicate.Payment(sql.FieldGTE(FieldAmountFiat, v))
}

// AmountFiatLT applies the LT predicate on the "amount_fiat" field.
func AmountFiatLT(v float64) predicate.Payment {
	return predicate.Payment(sql.FieldLT(FieldAmountFiat, v))
}

// AmountFiatLTE applies the LTE predicate on the "amount_fiat" field.
func AmountFiatLTE(v float64) predicate.Payment {
	return predicate.Payment(sql.FieldLTE(FieldAmountFiat, v))
}

// CurrencyFiatEQ applies the EQ predicate on the "currency_fiat" field.
func CurrencyFiatEQ(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldCurrencyFiat, v))
}

// CurrencyFiatNEQ applies the NEQ predicate on the "currency_fiat" field.
func CurrencyFiatNEQ(v string) predicate.Payment {
	return predicate.Payment(sql.FieldNEQ(FieldCurrencyFiat, v))
}

// CurrencyFiatIn applies the In predicate on the "currency_fiat" field.
func CurrencyFiatIn(vs ...string) predicate.Payment {
	return predicate.Payment(sql.FieldIn(FieldCurrencyFiat, vs...))
}

// CurrencyFiatNotIn applies the NotIn predicate on the "currency_fiat" field.
func CurrencyFiatNotIn(vs ...string) predicate.Payment {
	return predicate.Payment(sql.FieldNotIn(FieldCurrencyFiat, vs...))
}

// CurrencyFiatGT applies the GT predicate on the "currency_fiat" field.
func CurrencyFiatGT(v string) predicate.Payment {
	return predicate.Payment(sql.FieldGT(FieldCurrencyFiat, v))
}

// CurrencyFiatGTE applies the GTE predicate on the "currency_fiat" field.
func CurrencyFiatGTE(v string) predicate.Payment {
	return predicate.Payment(sql.FieldGTE(FieldCurrencyFiat, v))
}

// CurrencyFiatLT applies the LT predicate on the "currency_fiat" field.
func CurrencyFiatLT(v string) predicate.Payment {
	return predicate.Payment(sql.FieldLT(FieldCurrencyFiat, v))
}

// CurrencyFiatLTE applies the LTE predicate on the "currency_fiat" field.
func CurrencyFiatLTE(v string) predicate.Payment {
	return predicate.Payment(sql.FieldLTE(FieldCurrencyFiat, v))
}

// CurrencyFiatContains applies the Contains predicate on the "currency_fiat" field.
func CurrencyFiatContains(v string) predicate.Payment {
	return predicate.Payment(sql.FieldContains(FieldCurrencyFiat, v))
}

// CurrencyFiatHasPrefix applies the HasPrefix predicate on the "currency_fiat" field.
func CurrencyFiatHasPrefix(v string) predicate.Payment {
	return predicate.Payment(sql.FieldHasPrefix(FieldCurrencyFiat, v))
}

// CurrencyFiatHasSuffix applies the HasSuffix predicate on the "currency_fiat" field.
func CurrencyFiatHasSuffix(v string) predicate.Payment {
	return predicate.Payment(sql.FieldHasSuffix(FieldCurrencyFiat, v))
}

// CurrencyFiatEqualFold applies the EqualFold predicate on the "currency_fiat" field.
func CurrencyFiatEqualFold(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEqualFold(FieldCurrencyFiat, v))
}

// CurrencyFiatContainsFold applies the ContainsFold predicate on the "currency_fiat" field.
func CurrencyFiatContainsFold(v string) predicate.Payment {
	return predicate.Payment(sql.FieldContainsFold(FieldCurrencyFiat, v))
}

// ReceivedAmountEQ applies the EQ predicate on the "received_amount" field.
func ReceivedAmountEQ(v float64) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldReceivedAmount, v))
}

// ReceivedAmountNEQ applies the NEQ predicate on the "received_amount" field.
func ReceivedAmountNEQ(v float64) predicate.Payment {
	return predicate.Payment(sql.FieldNEQ(FieldReceivedAmount, v))
}

// ReceivedAmountIn applies the In predicate on the "received_amount" field.
func ReceivedAmountIn(vs ...float64) predicate.Payment {
	return predicate.Payment(sql.FieldIn(FieldReceivedAmount, vs...))
}

// ReceivedAmountNotIn applies the NotIn predicate on the "received_amount" field.
func ReceivedAmountNotIn(vs ...float64) predicate.Payment {
	return predicate.Payment(sql.FieldNotIn(FieldReceivedAmount, vs...))
}

// ReceivedAmountGT applies the GT predicate on the "received_amount" field.
func ReceivedAmountGT(v float64) predicate.Payment {
	return predicate.Payment(sql.FieldGT(FieldReceivedAmount, v))
}

// ReceivedAmountGTE applies the GTE predicate on the "received_amount" field.
func ReceivedAmountGTE(v float64) predicate.Payment {
	return predicate.Payment(sql.FieldGTE(FieldReceivedAmount, v))
}

// ReceivedAmountLT applies the LT predicate on the "received_amount" field.
func ReceivedAmountLT(v float64) predicate.Payment {
	return predicate.Payment(sql.FieldLT(FieldReceivedAmount, v))
}

// ReceivedAmountLTE applies the LTE predicate on the "received_amount" field.
func ReceivedAmountLTE(v float64) predicate.Payment {
	return predicate.Payment(sql.FieldLTE(FieldReceivedAmount, v))
}

// ReceivedAmountIsNil applies the IsNil predicate on the "received_amount" field.
func ReceivedAmountIsNil() predicate.Payment {
	return predicate.Payment(sql.FieldIsNull(FieldReceivedAmount))
}

// ReceivedAmountNotNil applies the NotNil predicate on the "received_amount" field.
func ReceivedAmountNotNil() predicate.Payment {
	return predicate.Payment(sql.FieldNotNull(FieldReceivedAmount))
}

// TransactionHashEQ applies the EQ predicate on the "transaction_hash" field.
func TransactionHashEQ(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldTransactionHash, v))
}

// TransactionHashNEQ applies the NEQ predicate on the "transaction_hash" field.
func TransactionHashNEQ(v string) predicate.Payment {
	return predicate.Payment(sql.FieldNEQ(FieldTransactionHash, v))
}

// TransactionHashIn applies the In predicate on the "transaction_hash" field.
func TransactionHashIn(vs ...string) predicate.Payment {
	return predicate.Payment(sql.FieldIn(FieldTransactionHash, vs...))
}

// TransactionHashNotIn applies the NotIn predicate on the "transaction_hash" field.
func TransactionHashNotIn(vs ...string) predicate.Payment {
	return predicate.Payment(sql.FieldNotIn(FieldTransactionHash, vs...))
}

// TransactionHashGT applies the GT predicate on the "transaction_hash" field.
func TransactionHashGT(v string) predicate.Payment {
	return predicate.Payment(sql.FieldGT(FieldTransactionHash, v))
}

// TransactionHashGTE applies the GTE predicate on the "transaction_hash" field.
func TransactionHashGTE(v string) predicate.Payment {
	return predicate.Payment(sql.FieldGTE(FieldTransactionHash, v))
}

// TransactionHashLT applies the LT predicate on the "transaction_hash" field.
func TransactionHashLT(v string) predicate.Payment {
	return predicate.Payment(sql.FieldLT(FieldTransactionHash, v))
}

// TransactionHashLTE applies the LTE predicate on the "transaction_hash" field.
func TransactionHashLTE(v string) predicate.Payment {
	return predicate.Payment(sql.FieldLTE(FieldTransactionHash, v))
}

// TransactionHashContains applies the Contains predicate on the "transaction_hash" field.
func TransactionHashContains(v string) predicate.Payment {
	return predicate.Payment(sql.FieldContains(FieldTransactionHash, v))
}

// TransactionHashHasPrefix applies the HasPrefix predicate on the "transaction_hash" field.
func TransactionHashHasPrefix(v string) predicate.Payment {
	return predicate.Payment(sql.FieldHasPrefix(FieldTransactionHash, v))
}

// TransactionHashHasSuffix applies the HasSuffix predicate on the "transaction_hash" field.
func TransactionHashHasSuffix(v string) predicate.Payment {
	return predicate.Payment(sql.FieldHasSuffix(FieldTransactionHash, v))
}

// TransactionHashIsNil applies the IsNil predicate on the "transaction_hash" field.
func TransactionHashIsNil() predicate.Payment {
	return predicate.Payment(sql.FieldIsNull(FieldTransactionHash))
}

// TransactionHashNotNil applies the NotNil predicate on the "transaction_hash" field.
func TransactionHashNotNil() predicate.Payment {
	return predicate.Payment(sql.FieldNotNull(FieldTransactionHash))
}

// TransactionHashEqualFold applies the EqualFold predicate on the "transaction_hash" field.
func TransactionHashEqualFold(v string) predicate.Payment {
	return predicate.Payment(sql.FieldEqualFold(FieldTransactionHash, v))
}

// TransactionHashContainsFold applies the ContainsFold predicate on the "transaction_hash" field.
func TransactionHashContainsFold(v string) predicate.Payment {
	return predicate.Payment(sql.FieldContainsFold(FieldTransactionHash, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Payment {
	return predicate.Payment(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Payment {
	return predicate.Payment(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Payment {
	return predicate.Payment(sql.FieldNotIn(FieldStatus, vs...))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.Payment {
	return predicate.Payment(sql.FieldLTE(FieldExpiresAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Payment {
	return predicate.Payment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Payment {
	return predicate.Payment(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Payment) predicate.Payment {
	return predicate.Payment(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Payment) predicate.Payment {
	return predicate.Payment(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Payment) predicate.Payment {
	return predicate.Payment(sql.NotPredicates(p))
}
