// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/szerookii/litepay/backend/ent/payment"
	"github.com/szerookii/litepay/backend/ent/predicate"
	"github.com/szerookii/litepay/backend/ent/user"
)

// PaymentUpdate is the builder for updating Payment entities.
type PaymentUpdate struct {
	config
	hooks    []Hook
	mutation *PaymentMutation
}

// Where appends a list predicates to the PaymentUpdate builder.
func (_u *PaymentUpdate) Where(ps ...predicate.Payment) *PaymentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *PaymentUpdate) SetUpdateTime(v time.Time) *PaymentUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *PaymentUpdate) SetUserID(v uuid.UUID) *PaymentUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableUserID(v *uuid.UUID) *PaymentUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetWalletAddress sets the "wallet_address" field.
func (_u *PaymentUpdate) SetWalletAddress(v string) *PaymentUpdate {
	_u.mutation.SetWalletAddress(v)
	return _u
}

// SetNillableWalletAddress sets the "wallet_address" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableWalletAddress(v *string) *PaymentUpdate {
	if v != nil {
		_u.SetWalletAddress(*v)
	}
	return _u
}

// SetSolReference sets the "sol_reference" field.
func (_u *PaymentUpdate) SetSolReference(v string) *PaymentUpdate {
	_u.mutation.SetSolReference(v)
	return _u
}

// SetNillableSolReference sets the "sol_reference" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableSolReference(v *string) *PaymentUpdate {
	if v != nil {
		_u.SetSolReference(*v)
	}
	return _u
}

// ClearSolReference clears the value of the "sol_reference" field.
func (_u *PaymentUpdate) ClearSolReference() *PaymentUpdate {
	_u.mutation.ClearSolReference()
	return _u
}

// SetAddressIndex sets the "address_index" field.
func (_u *PaymentUpdate) SetAddressIndex(v int) *PaymentUpdate {
	_u.mutation.ResetAddressIndex()
	_u.mutation.SetAddressIndex(v)
	return _u
}

// SetNillableAddressIndex sets the "address_index" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableAddressIndex(v *int) *PaymentUpdate {
	if v != nil {
		_u.SetAddressIndex(*v)
	}
	return _u
}

// AddAddressIndex adds value to the "address_index" field.
func (_u *PaymentUpdate) AddAddressIndex(v int) *PaymentUpdate {
	_u.mutation.AddAddressIndex(v)
	return _u
}

// SetAmountCrypto sets the "amount_crypto" field.
func (_u *PaymentUpdate) SetAmountCrypto(v float64) *PaymentUpdate {
	_u.mutation.ResetAmountCrypto()
	_u.mutation.SetAmountCrypto(v)
	return _u
}

// SetNillableAmountCrypto sets the "amount_crypto" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableAmountCrypto(v *float64) *PaymentUpdate {
	if v != nil {
		_u.SetAmountCrypto(*v)
	}
	return _u
}

// AddAmountCrypto adds value to the "amount_crypto" field.
func (_u *PaymentUpdate) AddAmountCrypto(v float64) *PaymentUpdate {
	_u.mutation.AddAmountCrypto(v)
	return _u
}

// SetCurrencyCrypto sets the "currency_crypto" field.
func (_u *PaymentUpdate) SetCurrencyCrypto(v string) *PaymentUpdate {
	_u.mutation.SetCurrencyCrypto(v)
	return _u
}

// SetNillableCurrencyCrypto sets the "currency_crypto" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableCurrencyCrypto(v *string) *PaymentUpdate {
	if v != nil {
		_u.SetCurrencyCrypto(*v)
	}
	return _u
}

// SetAmountFiat sets the "amount_fiat" field.
func (_u *PaymentUpdate) SetAmountFiat(v float64) *PaymentUpdate {
	_u.mutation.ResetAmountFiat()
	_u.mutation.SetAmountFiat(v)
	return _u
}

// SetNillableAmountFiat sets the "amount_fiat" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableAmountFiat(v *float64) *PaymentUpdate {
	if v != nil {
		_u.SetAmountFiat(*v)
	}
	return _u
}

// AddAmountFiat adds value to the "amount_fiat" field.
func (_u *PaymentUpdate) AddAmountFiat(v float64) *PaymentUpdate {
	_u.mutation.AddAmountFiat(v)
	return _u
}

// SetCurrencyFiat sets the "currency_fiat" field.
func (_u *PaymentUpdate) SetCurrencyFiat(v string) *PaymentUpdate {
	_u.mutation.SetCurrencyFiat(v)
	return _u
}

// SetNillableCurrencyFiat sets the "currency_fiat" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableCurrencyFiat(v *string) *PaymentUpdate {
	if v != nil {
		_u.SetCurrencyFiat(*v)
	}
	return _u
}

// SetReceivedAmount sets the "received_amount" field.
func (_u *PaymentUpdate) SetReceivedAmount(v float64) *PaymentUpdate {
	_u.mutation.ResetReceivedAmount()
	_u.mutation.SetReceivedAmount(v)
	return _u
}

// SetNillableReceivedAmount sets the "received_amount" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableReceivedAmount(v *float64) *PaymentUpdate {
	if v != nil {
		_u.SetReceivedAmount(*v)
	}
	return _u
}

// AddReceivedAmount adds value to the "received_amount" field.
func (_u *PaymentUpdate) AddReceivedAmount(v float64) *PaymentUpdate {
	_u.mutation.AddReceivedAmount(v)
	return _u
}

// ClearReceivedAmount clears the value of the "received_amount" field.
func (_u *PaymentUpdate) ClearReceivedAmount() *PaymentUpdate {
	_u.mutation.ClearReceivedAmount()
	return _u
}

// SetTransactionHash sets the "transaction_hash" field.
func (_u *PaymentUpdate) SetTransactionHash(v string) *PaymentUpdate {
	_u.mutation.SetTransactionHash(v)
	return _u
}

// SetNillableTransactionHash sets the "transaction_hash" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableTransactionHash(v *string) *PaymentUpdate {
	if v != nil {
		_u.SetTransactionHash(*v)
	}
	return _u
}

// ClearTransactionHash clears the value of the "transaction_hash" field.
func (_u *PaymentUpdate) ClearTransactionHash() *PaymentUpdate {
	_u.mutation.ClearTransactionHash()
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentUpdate) SetStatus(v payment.Status) *PaymentUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableStatus(v *payment.Status) *PaymentUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *PaymentUpdate) SetExpiresAt(v time.Time) *PaymentUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *PaymentUpdate) SetNillableExpiresAt(v *time.Time) *PaymentUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PaymentUpdate) SetUser(v *User) *PaymentUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the PaymentMutation object of the builder.
func (_u *PaymentUpdate) Mutation() *PaymentMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PaymentUpdate) ClearUser() *PaymentUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PaymentUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PaymentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := payment.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := payment.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Payment.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Payment.user"`)
	}
	return nil
}

func (_u *PaymentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(payment.Table, payment.Columns, sqlgraph.NewFieldSpec(payment.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(payment.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.WalletAddress(); ok {
		_spec.SetField(payment.FieldWalletAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.SolReference(); ok {
		_spec.SetField(payment.FieldSolReference, field.TypeString, value)
	}
	if _u.mutation.SolReferenceCleared() {
		_spec.ClearField(payment.FieldSolReference, field.TypeString)
	}
	if value, ok := _u.mutation.AddressIndex(); ok {
		_spec.SetField(payment.FieldAddressIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAddressIndex(); ok {
		_spec.AddField(payment.FieldAddressIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AmountCrypto(); ok {
		_spec.SetField(payment.FieldAmountCrypto, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmountCrypto(); ok {
		_spec.AddField(payment.FieldAmountCrypto, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CurrencyCrypto(); ok {
		_spec.SetField(payment.FieldCurrencyCrypto, field.TypeString, value)
	}
	if value, ok := _u.mutation.AmountFiat(); ok {
		_spec.SetField(payment.FieldAmountFiat, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmountFiat(); ok {
		_spec.AddField(payment.FieldAmountFiat, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CurrencyFiat(); ok {
		_spec.SetField(payment.FieldCurrencyFiat, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReceivedAmount(); ok {
		_spec.SetField(payment.FieldReceivedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedReceivedAmount(); ok {
		_spec.AddField(payment.FieldReceivedAmount, field.TypeFloat64, value)
	}
	if _u.mutation.ReceivedAmountCleared() {
		_spec.ClearField(payment.FieldReceivedAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.TransactionHash(); ok {
		_spec.SetField(payment.FieldTransactionHash, field.TypeString, value)
	}
	if _u.mutation.TransactionHashCleared() {
		_spec.ClearField(payment.FieldTransactionHash, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(payment.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(payment.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.UserTable,
			Columns: []string{payment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.UserTable,
			Columns: []string{payment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{payment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PaymentUpdateOne is the builder for updating a single Payment entity.
type PaymentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaymentMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *PaymentUpdateOne) SetUpdateTime(v time.Time) *PaymentUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *PaymentUpdateOne) SetUserID(v uuid.UUID) *PaymentUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableUserID(v *uuid.UUID) *PaymentUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetWalletAddress sets the "wallet_address" field.
func (_u *PaymentUpdateOne) SetWalletAddress(v string) *PaymentUpdateOne {
	_u.mutation.SetWalletAddress(v)
	return _u
}

// SetNillableWalletAddress sets the "wallet_address" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableWalletAddress(v *string) *PaymentUpdateOne {
	if v != nil {
		_u.SetWalletAddress(*v)
	}
	return _u
}

// SetSolReference sets the "sol_reference" field.
func (_u *PaymentUpdateOne) SetSolReference(v string) *PaymentUpdateOne {
	_u.mutation.SetSolReference(v)
	return _u
}

// SetNillableSolReference sets the "sol_reference" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableSolReference(v *string) *PaymentUpdateOne {
	if v != nil {
		_u.SetSolReference(*v)
	}
	return _u
}

// ClearSolReference clears the value of the "sol_reference" field.
func (_u *PaymentUpdateOne) ClearSolReference() *PaymentUpdateOne {
	_u.mutation.ClearSolReference()
	return _u
}

// SetAddressIndex sets the "address_index" field.
func (_u *PaymentUpdateOne) SetAddressIndex(v int) *PaymentUpdateOne {
	_u.mutation.ResetAddressIndex()
	_u.mutation.SetAddressIndex(v)
	return _u
}

// SetNillableAddressIndex sets the "address_index" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableAddressIndex(v *int) *PaymentUpdateOne {
	if v != nil {
		_u.SetAddressIndex(*v)
	}
	return _u
}

// AddAddressIndex adds value to the "address_index" field.
func (_u *PaymentUpdateOne) AddAddressIndex(v int) *PaymentUpdateOne {
	_u.mutation.AddAddressIndex(v)
	return _u
}

// SetAmountCrypto sets the "amount_crypto" field.
func (_u *PaymentUpdateOne) SetAmountCrypto(v float64) *PaymentUpdateOne {
	_u.mutation.ResetAmountCrypto()
	_u.mutation.SetAmountCrypto(v)
	return _u
}

// SetNillableAmountCrypto sets the "amount_crypto" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableAmountCrypto(v *float64) *PaymentUpdateOne {
	if v != nil {
		_u.SetAmountCrypto(*v)
	}
	return _u
}

// AddAmountCrypto adds value to the "amount_crypto" field.
func (_u *PaymentUpdateOne) AddAmountCrypto(v float64) *PaymentUpdateOne {
	_u.mutation.AddAmountCrypto(v)
	return _u
}

// SetCurrencyCrypto sets the "currency_crypto" field.
func (_u *PaymentUpdateOne) SetCurrencyCrypto(v string) *PaymentUpdateOne {
	_u.mutation.SetCurrencyCrypto(v)
	return _u
}

// SetNillableCurrencyCrypto sets the "currency_crypto" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableCurrencyCrypto(v *string) *PaymentUpdateOne {
	if v != nil {
		_u.SetCurrencyCrypto(*v)
	}
	return _u
}

// SetAmountFiat sets the "amount_fiat" field.
func (_u *PaymentUpdateOne) SetAmountFiat(v float64) *PaymentUpdateOne {
	_u.mutation.ResetAmountFiat()
	_u.mutation.SetAmountFiat(v)
	return _u
}

// SetNillableAmountFiat sets the "amount_fiat" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableAmountFiat(v *float64) *PaymentUpdateOne {
	if v != nil {
		_u.SetAmountFiat(*v)
	}
	return _u
}

// AddAmountFiat adds value to the "amount_fiat" field.
func (_u *PaymentUpdateOne) AddAmountFiat(v float64) *PaymentUpdateOne {
	_u.mutation.AddAmountFiat(v)
	return _u
}

// SetCurrencyFiat sets the "currency_fiat" field.
func (_u *PaymentUpdateOne) SetCurrencyFiat(v string) *PaymentUpdateOne {
	_u.mutation.SetCurrencyFiat(v)
	return _u
}

// SetNillableCurrencyFiat sets the "currency_fiat" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableCurrencyFiat(v *string) *PaymentUpdateOne {
	if v != nil {
		_u.SetCurrencyFiat(*v)
	}
	return _u
}

// SetReceivedAmount sets the "received_amount" field.
func (_u *PaymentUpdateOne) SetReceivedAmount(v float64) *PaymentUpdateOne {
	_u.mutation.ResetReceivedAmount()
	_u.mutation.SetReceivedAmount(v)
	return _u
}

// SetNillableReceivedAmount sets the "received_amount" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableReceivedAmount(v *float64) *PaymentUpdateOne {
	if v != nil {
		_u.SetReceivedAmount(*v)
	}
	return _u
}

// AddReceivedAmount adds value to the "received_amount" field.
func (_u *PaymentUpdateOne) AddReceivedAmount(v float64) *PaymentUpdateOne {
	_u.mutation.AddReceivedAmount(v)
	return _u
}

// ClearReceivedAmount clears the value of the "received_amount" field.
func (_u *PaymentUpdateOne) ClearReceivedAmount() *PaymentUpdateOne {
	_u.mutation.ClearReceivedAmount()
	return _u
}

// SetTransactionHash sets the "transaction_hash" field.
func (_u *PaymentUpdateOne) SetTransactionHash(v string) *PaymentUpdateOne {
	_u.mutation.SetTransactionHash(v)
	return _u
}

// SetNillableTransactionHash sets the "transaction_hash" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableTransactionHash(v *string) *PaymentUpdateOne {
	if v != nil {
		_u.SetTransactionHash(*v)
	}
	return _u
}

// ClearTransactionHash clears the value of the "transaction_hash" field.
func (_u *PaymentUpdateOne) ClearTransactionHash() *PaymentUpdateOne {
	_u.mutation.ClearTransactionHash()
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentUpdateOne) SetStatus(v payment.Status) *PaymentUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableStatus(v *payment.Status) *PaymentUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *PaymentUpdateOne) SetExpiresAt(v time.Time) *PaymentUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *PaymentUpdateOne) SetNillableExpiresAt(v *time.Time) *PaymentUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PaymentUpdateOne) SetUser(v *User) *PaymentUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the PaymentMutation object of the builder.
func (_u *PaymentUpdateOne) Mutation() *PaymentMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PaymentUpdateOne) ClearUser() *PaymentUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the PaymentUpdate builder.
func (_u *PaymentUpdateOne) Where(ps ...predicate.Payment) *PaymentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PaymentUpdateOne) Select(field string, fields ...string) *PaymentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Payment entity.
func (_u *PaymentUpdateOne) Save(ctx context.Context) (*Payment, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentUpdateOne) SaveX(ctx context.Context) *Payment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PaymentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := payment.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := payment.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Payment.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Payment.user"`)
	}
	return nil
}

func (_u *PaymentUpdateOne) sqlSave(ctx context.Context) (_node *Payment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(payment.Table, payment.Columns, sqlgraph.NewFieldSpec(payment.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Payment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, payment.FieldID)
		for _, f := range fields {
			if !payment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != payment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(payment.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.WalletAddress(); ok {
		_spec.SetField(payment.FieldWalletAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.SolReference(); ok {
		_spec.SetField(payment.FieldSolReference, field.TypeString, value)
	}
	if _u.mutation.SolReferenceCleared() {
		_spec.ClearField(payment.FieldSolReference, field.TypeString)
	}
	if value, ok := _u.mutation.AddressIndex(); ok {
		_spec.SetField(payment.FieldAddressIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAddressIndex(); ok {
		_spec.AddField(payment.FieldAddressIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AmountCrypto(); ok {
		_spec.SetField(payment.FieldAmountCrypto, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmountCrypto(); ok {
		_spec.AddField(payment.FieldAmountCrypto, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CurrencyCrypto(); ok {
		_spec.SetField(payment.FieldCurrencyCrypto, field.TypeString, value)
	}
	if value, ok := _u.mutation.AmountFiat(); ok {
		_spec.SetField(payment.FieldAmountFiat, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmountFiat(); ok {
		_spec.AddField(payment.FieldAmountFiat, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CurrencyFiat(); ok {
		_spec.SetField(payment.FieldCurrencyFiat, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReceivedAmount(); ok {
		_spec.SetField(payment.FieldReceivedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedReceivedAmount(); ok {
		_spec.AddField(payment.FieldReceivedAmount, field.TypeFloat64, value)
	}
	if _u.mutation.ReceivedAmountCleared() {
		_spec.ClearField(payment.FieldReceivedAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.TransactionHash(); ok {
		_spec.SetField(payment.FieldTransactionHash, field.TypeString, value)
	}
	if _u.mutation.TransactionHashCleared() {
		_spec.ClearField(payment.FieldTransactionHash, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(payment.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(payment.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.UserTable,
			Columns: []string{payment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.UserTable,
			Columns: []string{payment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Payment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{payment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
