// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/szerookii/litepay/backend/ent/payment"
	"github.com/szerookii/litepay/backend/ent/user"
)

// PaymentCreate is the builder for creating a Payment entity.
type PaymentCreate struct {
	config
	mutation *PaymentMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (_c *PaymentCreate) SetCreateTime(v time.Time) *PaymentCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *PaymentCreate) SetNillableCreateTime(v *time.Time) *PaymentCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *PaymentCreate) SetUpdateTime(v time.Time) *PaymentCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *PaymentCreate) SetNillableUpdateTime(v *time.Time) *PaymentCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *PaymentCreate) SetUserID(v uuid.UUID) *PaymentCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetWalletAddress sets the "wallet_address" field.
func (_c *PaymentCreate) SetWalletAddress(v string) *PaymentCreate {
	_c.mutation.SetWalletAddress(v)
	return _c
}

// SetSolReference sets the "sol_reference" field.
func (_c *PaymentCreate) SetSolReference(v string) *PaymentCreate {
	_c.mutation.SetSolReference(v)
	return _c
}

// SetNillableSolReference sets the "sol_reference" field if the given value is not nil.
func (_c *PaymentCreate) SetNillableSolReference(v *string) *PaymentCreate {
	if v != nil {
		_c.SetSolReference(*v)
	}
	return _c
}

// SetAddressIndex sets the "address_index" field.
func (_c *PaymentCreate) SetAddressIndex(v int) *PaymentCreate {
	_c.mutation.SetAddressIndex(v)
	return _c
}

// SetNillableAddressIndex sets the "address_index" field if the given value is not nil.
func (_c *PaymentCreate) SetNillableAddressIndex(v *int) *PaymentCreate {
	if v != nil {
		_c.SetAddressIndex(*v)
	}
	return _c
}

// SetAmountCrypto sets the "amount_crypto" field.
func (_c *PaymentCreate) SetAmountCrypto(v float64) *PaymentCreate {
	_c.mutation.SetAmountCrypto(v)
	return _c
}

// SetCurrencyCrypto sets the "currency_crypto" field.
func (_c *PaymentCreate) SetCurrencyCrypto(v string) *PaymentCreate {
	_c.mutation.SetCurrencyCrypto(v)
	return _c
}

// SetAmountFiat sets the "amount_fiat" field.
func (_c *PaymentCreate) SetAmountFiat(v float64) *PaymentCreate {
	_c.mutation.SetAmountFiat(v)
	return _c
}

// SetCurrencyFiat sets the "currency_fiat" field.
func (_c *PaymentCreate) SetCurrencyFiat(v string) *PaymentCreate {
	_c.mutation.SetCurrencyFiat(v)
	return _c
}

// SetReceivedAmount sets the "received_amount" field.
func (_c *PaymentCreate) SetReceivedAmount(v float64) *PaymentCreate {
	_c.mutation.SetReceivedAmount(v)
	return _c
}

// SetNillableReceivedAmount sets the "received_amount" field if the given value is not nil.
func (_c *PaymentCreate) SetNillableReceivedAmount(v *float64) *PaymentCreate {
	if v != nil {
		_c.SetReceivedAmount(*v)
	}
	return _c
}

// SetTransactionHash sets the "transaction_hash" field.
func (_c *PaymentCreate) SetTransactionHash(v string) *PaymentCreate {
	_c.mutation.SetTransactionHash(v)
	return _c
}

// SetNillableTransactionHash sets the "transaction_hash" field if the given value is not nil.
func (_c *PaymentCreate) SetNillableTransactionHash(v *string) *PaymentCreate {
	if v != nil {
		_c.SetTransactionHash(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *PaymentCreate) SetStatus(v payment.Status) *PaymentCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PaymentCreate) SetNillableStatus(v *payment.Status) *PaymentCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *PaymentCreate) SetExpiresAt(v time.Time) *PaymentCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *PaymentCreate) SetNillableExpiresAt(v *time.Time) *PaymentCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PaymentCreate) SetID(v uuid.UUID) *PaymentCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PaymentCreate) SetNillableID(v *uuid.UUID) *PaymentCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *PaymentCreate) SetUser(v *User) *PaymentCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the PaymentMutation object of the builder.
func (_c *PaymentCreate) Mutation() *PaymentMutation {
	return _c.mutation
}

// Save creates the Payment in the database.
func (_c *PaymentCreate) Save(ctx context.Context) (*Payment, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PaymentCreate) SaveX(ctx context.Context) *Payment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PaymentCreate) defaults() {
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := payment.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := payment.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.AddressIndex(); !ok {
		v := payment.DefaultAddressIndex
		_c.mutation.SetAddressIndex(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := payment.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		v := payment.DefaultExpiresAt()
		_c.mutation.SetExpiresAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := payment.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PaymentCreate) check() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "Payment.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "Payment.update_time"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Payment.user_id"`)}
	}
	if _, ok := _c.mutation.WalletAddress(); !ok {
		return &ValidationError{Name: "wallet_address", err: errors.New(`ent: missing required field "Payment.wallet_address"`)}
	}
	if _, ok := _c.mutation.AddressIndex(); !ok {
		return &ValidationError{Name: "address_index", err: errors.New(`ent: missing required field "Payment.address_index"`)}
	}
	if _, ok := _c.mutation.AmountCrypto(); !ok {
		return &ValidationError{Name: "amount_crypto", err: errors.New(`ent: missing required field "Payment.amount_crypto"`)}
	}
	if _, ok := _c.mutation.CurrencyCrypto(); !ok {
		return &ValidationError{Name: "currency_crypto", err: errors.New(`ent: missing required field "Payment.currency_crypto"`)}
	}
	if _, ok := _c.mutation.AmountFiat(); !ok {
		return &ValidationError{Name: "amount_fiat", err: errors.New(`ent: missing required field "Payment.amount_fiat"`)}
	}
	if _, ok := _c.mutation.CurrencyFiat(); !ok {
		return &ValidationError{Name: "currency_fiat", err: errors.New(`ent: missing required field "Payment.currency_fiat"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Payment.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := payment.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Payment.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "Payment.expires_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Payment.user"`)}
	}
	return nil
}

func (_c *PaymentCreate) sqlSave(ctx context.Context) (*Payment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PaymentCreate) createSpec() (*Payment, *sqlgraph.CreateSpec) {
	var (
		_node = &Payment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(payment.Table, sqlgraph.NewFieldSpec(payment.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(payment.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(payment.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.WalletAddress(); ok {
		_spec.SetField(payment.FieldWalletAddress, field.TypeString, value)
		_node.WalletAddress = value
	}
	if value, ok := _c.mutation.SolReference(); ok {
		_spec.SetField(payment.FieldSolReference, field.TypeString, value)
		_node.SolReference = &value
	}
	if value, ok := _c.mutation.AddressIndex(); ok {
		_spec.SetField(payment.FieldAddressIndex, field.TypeInt, value)
		_node.AddressIndex = value
	}
	if value, ok := _c.mutation.AmountCrypto(); ok {
		_spec.SetField(payment.FieldAmountCrypto, field.TypeFloat64, value)
		_node.AmountCrypto = value
	}
	if value, ok := _c.mutation.CurrencyCrypto(); ok {
		_spec.SetField(payment.FieldCurrencyCrypto, field.TypeString, value)
		_node.CurrencyCrypto = value
	}
	if value, ok := _c.mutation.AmountFiat(); ok {
		_spec.SetField(payment.FieldAmountFiat, field.TypeFloat64, value)
		_node.AmountFiat = value
	}
	if value, ok := _c.mutation.CurrencyFiat(); ok {
		_spec.SetField(payment.FieldCurrencyFiat, field.TypeString, value)
		_node.CurrencyFiat = value
	}
	if value, ok := _c.mutation.ReceivedAmount(); ok {
		_spec.SetField(payment.FieldReceivedAmount, field.TypeFloat64, value)
		_node.ReceivedAmount = &value
	}
	if value, ok := _c.mutation.TransactionHash(); ok {
		_spec.SetField(payment.FieldTransactionHash, field.TypeString, value)
		_node.TransactionHash = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(payment.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(payment.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.UserTable,
			Columns: []string{payment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PaymentCreateBulk is the builder for creating many Payment entities in bulk.
type PaymentCreateBulk struct {
	config
	err      error
	builders []*PaymentCreate
}

// Save creates the Payment entities in the database.
func (_c *PaymentCreateBulk) Save(ctx context.Context) ([]*Payment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Payment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PaymentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PaymentCreateBulk) SaveX(ctx context.Context) []*Payment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
