// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/szerookii/litepay/backend/ent/payment"
	"github.com/szerookii/litepay/backend/ent/user"
)

// Payment is the model entity for the Payment schema.
type Payment struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// WalletAddress holds the value of the "wallet_address" field.
	WalletAddress string `json:"wallet_address,omitempty"`
	// SolReference holds the value of the "sol_reference" field.
	SolReference *string `json:"sol_reference,omitempty"`
	// AddressIndex holds the value of the "address_index" field.
	AddressIndex int `json:"address_index,omitempty"`
	// AmountCrypto holds the value of the "amount_crypto" field.
	AmountCrypto float64 `json:"amount_crypto,omitempty"`
	// CurrencyCrypto holds the value of the "currency_crypto" field.
	CurrencyCrypto string `json:"currency_crypto,omitempty"`
	// AmountFiat holds the value of the "amount_fiat" field.
	AmountFiat float64 `json:"amount_fiat,omitempty"`
	// CurrencyFiat holds the value of the "currency_fiat" field.
	CurrencyFiat string `json:"currency_fiat,omitempty"`
	// ReceivedAmount holds the value of the "received_amount" field.
	ReceivedAmount *float64 `json:"received_amount,omitempty"`
	// TransactionHash holds the value of the "transaction_hash" field.
	TransactionHash *string `json:"transaction_hash,omitempty"`
	// Status holds the value of the "status" field.
	Status payment.Status `json:"status,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PaymentQuery when eager-loading is set.
	Edges        PaymentEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PaymentEdges holds the relations/edges for other nodes in the graph.
type PaymentEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PaymentEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Payment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case payment.FieldAmountCrypto, payment.FieldAmountFiat, payment.FieldReceivedAmount:
			values[i] = new(sql.NullFloat64)
		case payment.FieldAddressIndex:
			values[i] = new(sql.NullInt64)
		case payment.FieldWalletAddress, payment.FieldSolReference, payment.FieldCurrencyCrypto, payment.FieldCurrencyFiat, payment.FieldTransactionHash, payment.FieldStatus:
			values[i] = new(sql.NullString)
		case payment.FieldCreateTime, payment.FieldUpdateTime, payment.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		case payment.FieldID, payment.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Payment fields.
func (_m *Payment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case payment.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case payment.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		case payment.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = value.Time
			}
		case payment.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case payment.FieldWalletAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field wallet_address", values[i])
			} else if value.Valid {
				_m.WalletAddress = value.String
			}
		case payment.FieldSolReference:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sol_reference", values[i])
			} else if value.Valid {
				_m.SolReference = new(string)
				*_m.SolReference = value.String
			}
		case payment.FieldAddressIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field address_index", values[i])
			} else if value.Valid {
				_m.AddressIndex = int(value.Int64)
			}
		case payment.FieldAmountCrypto:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount_crypto", values[i])
			} else if value.Valid {
				_m.AmountCrypto = value.Float64
			}
		case payment.FieldCurrencyCrypto:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency_crypto", values[i])
			} else if value.Valid {
				_m.CurrencyCrypto = value.String
			}
		case payment.FieldAmountFiat:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount_fiat", values[i])
			} else if value.Valid {
				_m.AmountFiat = value.Float64
			}
		case payment.FieldCurrencyFiat:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency_fiat", values[i])
			} else if value.Valid {
				_m.CurrencyFiat = value.String
			}
		case payment.FieldReceivedAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field received_amount", values[i])
			} else if value.Valid {
				_m.ReceivedAmount = new(float64)
				*_m.ReceivedAmount = value.Float64
			}
		case payment.FieldTransactionHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field transaction_hash", values[i])
			} else if value.Valid {
				_m.TransactionHash = new(string)
				*_m.TransactionHash = value.String
			}
		case payment.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = payment.Status(value.String)
			}
		case payment.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Payment.
// This includes values selected through modifiers, order, etc.
func (_m *Payment) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Payment entity.
func (_m *Payment) QueryUser() *UserQuery {
	return NewPaymentClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this Payment.
// Note that you need to call Payment.Unwrap() before calling this method if this Payment
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Payment) Update() *PaymentUpdateOne {
	return NewPaymentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Payment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Payment) Unwrap() *Payment {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Payment is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Payment) String() string {
	var builder strings.Builder
	builder.WriteString("Payment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("create_time=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(_m.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("wallet_address=")
	builder.WriteString(_m.WalletAddress)
	builder.WriteString(", ")
	if v := _m.SolReference; v != nil {
		builder.WriteString("sol_reference=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("address_index=")
	builder.WriteString(fmt.Sprintf("%v", _m.AddressIndex))
	builder.WriteString(", ")
	builder.WriteString("amount_crypto=")
	builder.WriteString(fmt.Sprintf("%v", _m.AmountCrypto))
	builder.WriteString(", ")
	builder.WriteString("currency_crypto=")
	builder.WriteString(_m.CurrencyCrypto)
	builder.WriteString(", ")
	builder.WriteString("amount_fiat=")
	builder.WriteString(fmt.Sprintf("%v", _m.AmountFiat))
	builder.WriteString(", ")
	builder.WriteString("currency_fiat=")
	builder.WriteString(_m.CurrencyFiat)
	builder.WriteString(", ")
	if v := _m.ReceivedAmount; v != nil {
		builder.WriteString("received_amount=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.TransactionHash; v != nil {
		builder.WriteString("transaction_hash=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Payments is a parsable slice of Payment.
type Payments []*Payment
