// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/szerookii/litepay/backend/ent/payment"
	"github.com/szerookii/litepay/backend/ent/predicate"
	"github.com/szerookii/litepay/backend/ent/user"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *UserUpdate) SetUpdateTime(v time.Time) *UserUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdate) SetEmail(v string) *UserUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdate) SetNillableEmail(v *string) *UserUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *UserUpdate) SetPasswordHash(v string) *UserUpdate {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *UserUpdate) SetNillablePasswordHash(v *string) *UserUpdate {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetAPIKey sets the "api_key" field.
func (_u *UserUpdate) SetAPIKey(v string) *UserUpdate {
	_u.mutation.SetAPIKey(v)
	return _u
}

// SetNillableAPIKey sets the "api_key" field if the given value is not nil.
func (_u *UserUpdate) SetNillableAPIKey(v *string) *UserUpdate {
	if v != nil {
		_u.SetAPIKey(*v)
	}
	return _u
}

// SetAccountIndex sets the "account_index" field.
func (_u *UserUpdate) SetAccountIndex(v int) *UserUpdate {
	_u.mutation.ResetAccountIndex()
	_u.mutation.SetAccountIndex(v)
	return _u
}

// SetNillableAccountIndex sets the "account_index" field if the given value is not nil.
func (_u *UserUpdate) SetNillableAccountIndex(v *int) *UserUpdate {
	if v != nil {
		_u.SetAccountIndex(*v)
	}
	return _u
}

// AddAccountIndex adds value to the "account_index" field.
func (_u *UserUpdate) AddAccountIndex(v int) *UserUpdate {
	_u.mutation.AddAccountIndex(v)
	return _u
}

// SetWebhookURL sets the "webhook_url" field.
func (_u *UserUpdate) SetWebhookURL(v string) *UserUpdate {
	_u.mutation.SetWebhookURL(v)
	return _u
}

// SetNillableWebhookURL sets the "webhook_url" field if the given value is not nil.
func (_u *UserUpdate) SetNillableWebhookURL(v *string) *UserUpdate {
	if v != nil {
		_u.SetWebhookURL(*v)
	}
	return _u
}

// ClearWebhookURL clears the value of the "webhook_url" field.
func (_u *UserUpdate) ClearWebhookURL() *UserUpdate {
	_u.mutation.ClearWebhookURL()
	return _u
}

// SetWebhookSecret sets the "webhook_secret" field.
func (_u *UserUpdate) SetWebhookSecret(v string) *UserUpdate {
	_u.mutation.SetWebhookSecret(v)
	return _u
}

// SetNillableWebhookSecret sets the "webhook_secret" field if the given value is not nil.
func (_u *UserUpdate) SetNillableWebhookSecret(v *string) *UserUpdate {
	if v != nil {
		_u.SetWebhookSecret(*v)
	}
	return _u
}

// ClearWebhookSecret clears the value of the "webhook_secret" field.
func (_u *UserUpdate) ClearWebhookSecret() *UserUpdate {
	_u.mutation.ClearWebhookSecret()
	return _u
}

// AddPaymentIDs adds the "payments" edge to the Payment entity by IDs.
func (_u *UserUpdate) AddPaymentIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.AddPaymentIDs(ids...)
	return _u
}

// AddPayments adds the "payments" edges to the Payment entity.
func (_u *UserUpdate) AddPayments(v ...*Payment) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPaymentIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// ClearPayments clears all "payments" edges to the Payment entity.
func (_u *UserUpdate) ClearPayments() *UserUpdate {
	_u.mutation.ClearPayments()
	return _u
}

// RemovePaymentIDs removes the "payments" edge to Payment entities by IDs.
func (_u *UserUpdate) RemovePaymentIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.RemovePaymentIDs(ids...)
	return _u
}

// RemovePayments removes "payments" edges to Payment entities.
func (_u *UserUpdate) RemovePayments(v ...*Payment) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePaymentIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := user.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdate) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(user.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(user.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKey(); ok {
		_spec.SetField(user.FieldAPIKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountIndex(); ok {
		_spec.SetField(user.FieldAccountIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAccountIndex(); ok {
		_spec.AddField(user.FieldAccountIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.WebhookURL(); ok {
		_spec.SetField(user.FieldWebhookURL, field.TypeString, value)
	}
	if _u.mutation.WebhookURLCleared() {
		_spec.ClearField(user.FieldWebhookURL, field.TypeString)
	}
	if value, ok := _u.mutation.WebhookSecret(); ok {
		_spec.SetField(user.FieldWebhookSecret, field.TypeString, value)
	}
	if _u.mutation.WebhookSecretCleared() {
		_spec.ClearField(user.FieldWebhookSecret, field.TypeString)
	}
	if _u.mutation.PaymentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PaymentsTable,
			Columns: []string{user.PaymentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPaymentsIDs(); len(nodes) > 0 && !_u.mutation.PaymentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PaymentsTable,
			Columns: []string{user.PaymentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PaymentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PaymentsTable,
			Columns: []string{user.PaymentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *UserUpdateOne) SetUpdateTime(v time.Time) *UserUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdateOne) SetEmail(v string) *UserUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableEmail(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *UserUpdateOne) SetPasswordHash(v string) *UserUpdateOne {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillablePasswordHash(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetAPIKey sets the "api_key" field.
func (_u *UserUpdateOne) SetAPIKey(v string) *UserUpdateOne {
	_u.mutation.SetAPIKey(v)
	return _u
}

// SetNillableAPIKey sets the "api_key" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableAPIKey(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetAPIKey(*v)
	}
	return _u
}

// SetAccountIndex sets the "account_index" field.
func (_u *UserUpdateOne) SetAccountIndex(v int) *UserUpdateOne {
	_u.mutation.ResetAccountIndex()
	_u.mutation.SetAccountIndex(v)
	return _u
}

// SetNillableAccountIndex sets the "account_index" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableAccountIndex(v *int) *UserUpdateOne {
	if v != nil {
		_u.SetAccountIndex(*v)
	}
	return _u
}

// AddAccountIndex adds value to the "account_index" field.
func (_u *UserUpdateOne) AddAccountIndex(v int) *UserUpdateOne {
	_u.mutation.AddAccountIndex(v)
	return _u
}

// SetWebhookURL sets the "webhook_url" field.
func (_u *UserUpdateOne) SetWebhookURL(v string) *UserUpdateOne {
	_u.mutation.SetWebhookURL(v)
	return _u
}

// SetNillableWebhookURL sets the "webhook_url" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableWebhookURL(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetWebhookURL(*v)
	}
	return _u
}

// ClearWebhookURL clears the value of the "webhook_url" field.
func (_u *UserUpdateOne) ClearWebhookURL() *UserUpdateOne {
	_u.mutation.ClearWebhookURL()
	return _u
}

// SetWebhookSecret sets the "webhook_secret" field.
func (_u *UserUpdateOne) SetWebhookSecret(v string) *UserUpdateOne {
	_u.mutation.SetWebhookSecret(v)
	return _u
}

// SetNillableWebhookSecret sets the "webhook_secret" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableWebhookSecret(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetWebhookSecret(*v)
	}
	return _u
}

// ClearWebhookSecret clears the value of the "webhook_secret" field.
func (_u *UserUpdateOne) ClearWebhookSecret() *UserUpdateOne {
	_u.mutation.ClearWebhookSecret()
	return _u
}

// AddPaymentIDs adds the "payments" edge to the Payment entity by IDs.
func (_u *UserUpdateOne) AddPaymentIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.AddPaymentIDs(ids...)
	return _u
}

// AddPayments adds the "payments" edges to the Payment entity.
func (_u *UserUpdateOne) AddPayments(v ...*Payment) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPaymentIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// ClearPayments clears all "payments" edges to the Payment entity.
func (_u *UserUpdateOne) ClearPayments() *UserUpdateOne {
	_u.mutation.ClearPayments()
	return _u
}

// RemovePaymentIDs removes the "payments" edge to Payment entities by IDs.
func (_u *UserUpdateOne) RemovePaymentIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.RemovePaymentIDs(ids...)
	return _u
}

// RemovePayments removes "payments" edges to Payment entities.
func (_u *UserUpdateOne) RemovePayments(v ...*Payment) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePaymentIDs(ids...)
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := user.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdateOne) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(user.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(user.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKey(); ok {
		_spec.SetField(user.FieldAPIKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountIndex(); ok {
		_spec.SetField(user.FieldAccountIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAccountIndex(); ok {
		_spec.AddField(user.FieldAccountIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.WebhookURL(); ok {
		_spec.SetField(user.FieldWebhookURL, field.TypeString, value)
	}
	if _u.mutation.WebhookURLCleared() {
		_spec.ClearField(user.FieldWebhookURL, field.TypeString)
	}
	if value, ok := _u.mutation.WebhookSecret(); ok {
		_spec.SetField(user.FieldWebhookSecret, field.TypeString, value)
	}
	if _u.mutation.WebhookSecretCleared() {
		_spec.ClearField(user.FieldWebhookSecret, field.TypeString)
	}
	if _u.mutation.PaymentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PaymentsTable,
			Columns: []string{user.PaymentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPaymentsIDs(); len(nodes) > 0 && !_u.mutation.PaymentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PaymentsTable,
			Columns: []string{user.PaymentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PaymentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PaymentsTable,
			Columns: []string{user.PaymentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
