// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// PaymentsColumns holds the columns for the "payments" table.
	PaymentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "wallet_address", Type: field.TypeString},
		{Name: "sol_reference", Type: field.TypeString, Nullable: true},
		{Name: "address_index", Type: field.TypeInt, Default: 0},
		{Name: "amount_crypto", Type: field.TypeFloat64},
		{Name: "currency_crypto", Type: field.TypeString},
		{Name: "amount_fiat", Type: field.TypeFloat64},
		{Name: "currency_fiat", Type: field.TypeString},
		{Name: "received_amount", Type: field.TypeFloat64, Nullable: true},
		{Name: "transaction_hash", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"PENDING", "CONFIRMING", "PAID", "EXPIRED", "REFUNDED", "CASHED_OUT"}, Default: "PENDING"},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// PaymentsTable holds the schema information for the "payments" table.
	PaymentsTable = &schema.Table{
		Name:       "payments",
		Columns:    PaymentsColumns,
		PrimaryKey: []*schema.Column{PaymentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "payments_users_payments",
				Columns:    []*schema.Column{PaymentsColumns[14]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "payment_wallet_address",
				Unique:  false,
				Columns: []*schema.Column{PaymentsColumns[3]},
			},
			{
				Name:    "payment_user_id",
				Unique:  false,
				Columns: []*schema.Column{PaymentsColumns[14]},
			},
			{
				Name:    "payment_sol_reference",
				Unique:  false,
				Columns: []*schema.Column{PaymentsColumns[4]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "email", Type: field.TypeString, Size: 255},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "api_key", Type: field.TypeString, Unique: true},
		{Name: "account_index", Type: field.TypeInt, Unique: true},
		{Name: "webhook_url", Type: field.TypeString, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_email",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[3]},
			},
			{
				Name:    "user_api_key",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[5]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PaymentsTable,
		UsersTable,
	}
)

func init() {
	PaymentsTable.ForeignKeys[0].RefTable = UsersTable
}
